mlopatkin/andlogview

src/name/mlopatkin/andlogview/Main.java
src/name/mlopatkin/andlogview/MainFrame.java
src/name/mlopatkin/andlogview/utils/SystemUtils.java
src/name/mlopatkin/andlogview/widgets/UiHelper.java

- Use global menu bar for JMenuBar.
- Force light appearance to fix swing rendering black-on-black text.
- Use platform-specific shortcut modifiers.

[macos] Basic UI support for macOS.

---

.github/actions/common-linux-setup/action.yml
.github/workflows/release-snapshot.yaml
.github/workflows/release.yaml

So far releases are only published to Bitbucket :)
Issue: #175

Add Github Workflows to build and publish releases

---

.github/workflows/pull-request-test.yaml
.github/workflows/release-snapshot.yaml
.github/workflows/release.yaml

Fix various issues in Github Workflow files

---

.github/workflows/release.yaml

Fix workflow name for non-snapshot release builds

---

.github/actions/common-linux-setup/action.yml
.gitignore
gradle.properties

Enable Gradle build cache for everything

---

src/name/mlopatkin/andlogview/device/DispatchingDeviceList.java

Always register listener first and add initial state later. Otherwise,
there may be a gap between the moment when the initial state is
captured and when the listener starts receiving events. If something is
added during this gap - it is lost forever.

Fix race condition in DispatchingDeviceList

---

AUTHORS.md
build.gradle
config/idea/copyright/Andlogview_APL_2_0.xml
config/idea/copyright/MLopatkin_APL_2_0.xml
config/idea/copyright/profiles_settings.xml
src/name/mlopatkin/andlogview/Main.java
src/name/mlopatkin/andlogview/MainFrame.java
src/name/mlopatkin/andlogview/config/Configuration.java
src/name/mlopatkin/andlogview/widgets/UiHelper.java

Add AUTHORS file and update copyrights

---

AUTHORS.md

Slighlty better formatting and spam prevention

---

build.gradle

Shrink libraries with Shadow plugin's minimizer

---

.github/workflows/release-snapshot.yaml

Publish snapshot release to Github releases

---

buildSrc/src/main/java/name/mlopatkin/andlogview/building/GenerateNotices.java

Fix accidental platform-specific EOLNs in the generated NOTICE file

---

src/name/mlopatkin/andlogview/liblogcat/ProcessListParser.java
src/name/mlopatkin/andlogview/utils/LineParser.java
test/name/mlopatkin/andlogview/liblogcat/ProcessListParserTest.java
test/name/mlopatkin/andlogview/utils/LineParserTest.java

Parse new process states

---

src/name/mlopatkin/andlogview/Main.java
src/name/mlopatkin/andlogview/ui/themes/MacOsSystemTheme.java

Set up Mac-specific preferences for all L&Fs

---

src/name/mlopatkin/andlogview/AtExitManager.java

Make AtExitManager thread-safe

---

HISTORY
src/name/mlopatkin/andlogview/liblogcat/LogRecordParser.java
src/name/mlopatkin/andlogview/ui/logtable/LogRecordTableColumnModel.java
test/name/mlopatkin/andlogview/liblogcat/LogRecordParserTest.java

Some minor fixes

---

build.gradle.kts
src/name/mlopatkin/andlogview/MainFrame.java
src/name/mlopatkin/andlogview/ui/filterpanel/FilterPanel.java
src/name/mlopatkin/andlogview/ui/filterpanel/FilterPanelUi.java
src/name/mlopatkin/andlogview/ui/themes/BasicWidgetFactory.java
src/name/mlopatkin/andlogview/ui/themes/FlatLafWidgetFactory.java
src/name/mlopatkin/andlogview/ui/themes/ThemedWidgetFactory.java

Use flatlaf scaling consistently

---

.github/workflows/publish-docker-environment.yaml
.gitignore
tools/build-environment/Dockerfile

Add a Dockerfile to build the build environment image

---

.github/workflows/publish-docker-environment.yaml

Fix image name in the docker image workflow

---

.github/workflows/release-snapshot.yaml
.github/workflows/release.yaml

Remove obsolete references to the old caching action from workflows

---

device/src/main/java/name/mlopatkin/andlogview/device/Device.java
device/src/main/java/name/mlopatkin/andlogview/device/ProvisionalDevice.java
device/src/main/java/name/mlopatkin/andlogview/device/ProvisionalDeviceImpl.java
src/name/mlopatkin/andlogview/ui/device/DeviceListCellRenderer.java
src/name/mlopatkin/andlogview/ui/device/DeviceListModel.java
src/name/mlopatkin/andlogview/ui/device/DeviceSelectionModel.java
src/name/mlopatkin/andlogview/ui/device/SelectDeviceDialog.java

These are not usable anyway.
Issue: fixes #260

Do not allow selecting provisional or offline devices in the dialog

---

.github/workflows/mirror-to-bitbucket.yaml
tools/bitbucket-mirror/cleanup.sh
tools/bitbucket-mirror/env.sh
tools/bitbucket-mirror/setup-bitbucket.sh

Add Github action to mirror to bitbucket automatically

---

tools/bitbucket-mirror/cleanup.sh
tools/bitbucket-mirror/setup-bitbucket.sh

Fix some issues with ssh configuration of bitbucket

---

BUILDING.md
buildSrc/src/main/kotlin/name/mlopatkin/andlogview/building/Utils.kt
buildSrc/src/main/kotlin/name/mlopatkin/andlogview/building/java-conventions.gradle.kts
gradle/libs.versions.toml
src/name/mlopatkin/andlogview/widgets/TextFieldVerifier.java
test/name/mlopatkin/andlogview/preferences/WindowsPositionsPrefTest.java

Use Jabel in build

---

src/name/mlopatkin/andlogview/FileTransferHandler.java
src/name/mlopatkin/andlogview/Main.java
src/name/mlopatkin/andlogview/MainFrame.java
src/name/mlopatkin/andlogview/liblogcat/file/DumpstateFileDataSource.java
src/name/mlopatkin/andlogview/liblogcat/file/FileDataSourceFactory.java
src/name/mlopatkin/andlogview/liblogcat/file/ImportProblem.java
src/name/mlopatkin/andlogview/liblogcat/file/ImportResult.java
src/name/mlopatkin/andlogview/liblogcat/file/LogfileDataSource.java
src/name/mlopatkin/andlogview/ui/file/FileOpener.java
src/name/mlopatkin/andlogview/ui/mainframe/MainFrameDependencies.java
test/name/mlopatkin/andlogview/liblogcat/file/FileDataSourceFactoryTest.java

Adds infrastructure for #277, partially addresses #248.

Show warnings for dumpstate import problems

---

parsers/src/main/java/name/mlopatkin/andlogview/parsers/dumpstate/DumpstateParseEventsHandler.java
parsers/src/main/java/name/mlopatkin/andlogview/parsers/dumpstate/LogcatSectionHandler.java
parsers/src/test/java/name/mlopatkin/andlogview/parsers/dumpstate/DumpstatePushParserHandlerTest.java
parsers/src/test/java/name/mlopatkin/andlogview/parsers/dumpstate/DumpstatePushParserTest.java
parsers/src/test/java/name/mlopatkin/andlogview/parsers/dumpstate/LogcatSectionHandlerTest.java
src/name/mlopatkin/andlogview/liblogcat/file/DumpstateFileDataSource.java

Handle more warning cases: invalid logcat and ps sections

---

logmodel/src/main/java/name/mlopatkin/andlogview/logmodel/order/OfflineSorter.java
logmodel/src/test/java/name/mlopatkin/andlogview/logmodel/order/OfflineSorterTest.java
src/name/mlopatkin/andlogview/liblogcat/file/DumpstateFileDataSource.java
test/name/mlopatkin/andlogview/liblogcat/file/FileDataSourceFactoryTest.java

Some fixes for time travel handling

---

.github/workflows/pull-request-test.yaml
.github/workflows/releasing.yaml

Updated Git to 1:2.25.1-1ubuntu3.10

Rebuild docker image to pick up latest Git

---

.gitignore
base/src/main/java/name/mlopatkin/andlogview/utils/MyStringUtils.java
parsers/src/main/java/name/mlopatkin/andlogview/parsers/logcat/DelegateLong.java
parsers/src/main/java/name/mlopatkin/andlogview/parsers/logcat/Format.java
parsers/src/main/java/name/mlopatkin/andlogview/parsers/logcat/LogcatPushParser.java
parsers/src/main/java/name/mlopatkin/andlogview/parsers/logcat/RegexLogcatParserDelegate.java
parsers/src/test/java/name/mlopatkin/andlogview/parsers/logcat/DelegateLongTest.java
parsers/src/test/java/name/mlopatkin/andlogview/parsers/logcat/SingleEntryParser.java
test/name/mlopatkin/andlogview/liblogcat/file/FileDataSourceFactoryTest.java
test_resources/name/mlopatkin/andlogview/liblogcat/file/emulator_api31_long.log

Parse long logcat format

---

.github/workflows/publish-docker-environment.yaml
.github/workflows/pull-request-test.yaml
.github/workflows/releasing.yaml
tools/build-environment/Dockerfile

Rebuild build environment with newer Java and git warning fix

---

base/src/main/java/name/mlopatkin/andlogview/utils/SystemPathResolver.java
base/src/test/java/name/mlopatkin/andlogview/utils/WindowsPathResolverTest.java

Quote character is actually allowed and meaningful, at least on Windows 10 where I tested it. Quotes can be used to have directory with a semicolon inside in the PATH.
Issue: #306

Fix handling of quotes in Windows PATH handling

---

device/src/main/java/name/mlopatkin/andlogview/device/CommandImpl.java
parsers/src/main/java/name/mlopatkin/andlogview/parsers/logcat/Format.java
parsers/src/main/java/name/mlopatkin/andlogview/parsers/logcat/LogcatParsers.java
parsers/src/test/java/name/mlopatkin/andlogview/parsers/logcat/DelegateLongTest.java
src/name/mlopatkin/andlogview/liblogcat/ddmlib/AdbBuffer.java
src/name/mlopatkin/andlogview/liblogcat/ddmlib/AdbDataSource.java
src/name/mlopatkin/andlogview/liblogcat/ddmlib/LogcatCommand.java

Use long format for adb

---

src/name/mlopatkin/andlogview/liblogcat/ddmlib/AdbBuffer.java

Remove accidental debug logging

---

src/name/mlopatkin/andlogview/config/ConfigStorage.java
test/name/mlopatkin/andlogview/config/ConfigStorageFactoryTest.java

Apparently Files.touch is not as good as I thought.
Fixes #317

Create parent directories when creating the configuration file

---

base/src/main/java/name/mlopatkin/andlogview/utils/MyFutures.java
device/src/main/java/name/mlopatkin/andlogview/device/DispatchingDeviceList.java
src/name/mlopatkin/andlogview/Main.java
src/name/mlopatkin/andlogview/MainFrame.java
src/name/mlopatkin/andlogview/ui/device/AdbServicesBridge.java
test/name/mlopatkin/andlogview/ui/device/AdbServicesBridgeTest.java

Now ADB server starts without blocking the UI
Fixes #205.

Non-blocking start of ADB server

---

HISTORY
base/src/main/java/name/mlopatkin/andlogview/base/MyThrowables.java
base/src/main/java/name/mlopatkin/andlogview/utils/Threads.java
base/src/testFixtures/java/name/mlopatkin/andlogview/base/concurrent/TestExecutor.java
base/src/testFixtures/java/name/mlopatkin/andlogview/utils/MockUiThreadScheduler.java
src/name/mlopatkin/andlogview/ui/device/AdbServicesBridge.java
src/name/mlopatkin/andlogview/ui/device/AdbServicesStatus.java
src/name/mlopatkin/andlogview/ui/device/AdbServicesSubcomponent.java
src/name/mlopatkin/andlogview/ui/status/SourceStatusPresenter.java
src/name/mlopatkin/andlogview/ui/status/SourceStatusViewImpl.java
test/name/mlopatkin/andlogview/ui/device/AdbServicesBridgeTest.java
test/name/mlopatkin/andlogview/ui/status/SourceStatusPresenterTest.java

Show ADB init status

---

build.gradle.kts
buildSrc/src/main/java/name/mlopatkin/andlogview/building/GenerateBuildMetadata.java
buildSrc/src/main/kotlin/name/mlopatkin/andlogview/building/metadata.gradle.kts

Improve cache hit when BuildInfo changes

---

base/src/main/java/name/mlopatkin/andlogview/utils/MyFutures.java
device/src/main/java/name/mlopatkin/andlogview/device/AdbDeviceList.java
src/name/mlopatkin/andlogview/FileTransferHandler.java
src/name/mlopatkin/andlogview/Main.java
src/name/mlopatkin/andlogview/MainFrame.java
src/name/mlopatkin/andlogview/filters/MainFilterController.java
src/name/mlopatkin/andlogview/ui/PendingDataSource.java
src/name/mlopatkin/andlogview/ui/device/AdbDataSourceFactory.java
src/name/mlopatkin/andlogview/ui/device/AdbOpener.java
src/name/mlopatkin/andlogview/ui/device/AdbServicesBridge.java
src/name/mlopatkin/andlogview/ui/device/AdbServicesInitializationPresenter.java
src/name/mlopatkin/andlogview/ui/file/FileOpener.java
src/name/mlopatkin/andlogview/ui/mainframe/MainFrameModule.java
src/name/mlopatkin/andlogview/ui/mainframe/device/MainFrameAdbInitView.java
src/name/mlopatkin/andlogview/ui/mainframe/device/MainFrameAdbModule.java
src/name/mlopatkin/andlogview/ui/mainframe/device/package-info.java
src/name/mlopatkin/andlogview/ui/search/SearchPresenter.java
test/name/mlopatkin/andlogview/test/ThreadTestUtils.java
test/name/mlopatkin/andlogview/ui/PendingDataSourceTest.java
test/name/mlopatkin/andlogview/ui/device/AdbServicesBridgeTest.java
test/name/mlopatkin/andlogview/ui/device/AdbServicesInitializationPresenterTest.java

Better ADB error handling

---

base/src/main/java/name/mlopatkin/andlogview/utils/SwingUiThreadScheduler.java
src/name/mlopatkin/andlogview/liblogcat/ddmlib/AdbDataSource.java
src/name/mlopatkin/andlogview/ui/status/SourceStatusPresenter.java
test/name/mlopatkin/andlogview/ui/status/SourceStatusPresenterTest.java

Fix source status not updating

---

base/build.gradle.kts
build.gradle.kts
buildSrc/src/main/kotlin/name/mlopatkin/andlogview/building/java-conventions.gradle.kts
device/build.gradle.kts
gradle/libs.versions.toml
logmodel/build.gradle.kts
parsers/build.gradle.kts
parsers/src/main/java/name/mlopatkin/andlogview/parsers/AbstractBasePushParser.java
parsers/src/main/java/name/mlopatkin/andlogview/parsers/AbstractPushParser.java
parsers/src/main/java/name/mlopatkin/andlogview/parsers/MultiplexParser.java
parsers/src/main/java/name/mlopatkin/andlogview/parsers/dumpstate/BaseDumpstatePushParser.java
parsers/src/main/java/name/mlopatkin/andlogview/parsers/dumpstate/DumpstateElements.java
parsers/src/main/java/name/mlopatkin/andlogview/parsers/dumpstate/DumpstateFormatSniffer.java
parsers/src/main/java/name/mlopatkin/andlogview/parsers/dumpstate/DumpstateParseEventsHandler.java
parsers/src/main/java/name/mlopatkin/andlogview/parsers/dumpstate/DumpstatePushParserHandler.java
parsers/src/main/java/name/mlopatkin/andlogview/parsers/dumpstate/ProcessEventsHandler.java
parsers/src/main/java/name/mlopatkin/andlogview/parsers/dumpstate/ProcessWaitChannelsParser.java
parsers/src/main/java/name/mlopatkin/andlogview/parsers/logcat/DelegateThreadTime.java
parsers/src/main/java/name/mlopatkin/andlogview/parsers/logcat/LogcatFormatSniffer.java
parsers/src/main/java/name/mlopatkin/andlogview/parsers/logcat/LogcatPushParser.java
parsers/src/main/java/name/mlopatkin/andlogview/parsers/ps/PsPushParser.java
parsers/src/test/java/name/mlopatkin/andlogview/parsers/dumpstate/ProcessWaitChannelsParserTest.java
parsers/src/test/java/name/mlopatkin/andlogview/parsers/logcat/DelegateThreadTimeTest.java
search/build.gradle.kts
search/logrecord/build.gradle.kts
src/name/mlopatkin/andlogview/liblogcat/file/DumpstateFileDataSource.java

Parse dumpstate processes out of BLOCKED PROCESS section

---

src/name/mlopatkin/andlogview/ui/bookmarks/BookmarkController.java
src/name/mlopatkin/andlogview/ui/bookmarks/BookmarkPopupMenuPresenter.java
src/name/mlopatkin/andlogview/ui/bookmarks/BookmarksDi.java
src/name/mlopatkin/andlogview/ui/bookmarks/DeleteBookmarksAction.java

The wiring is messy, but I need a consistent way of managing these shortcuts first. Then I'll rewrite
Fixes #149

Delete selected bookmarks on DEL button press

---

base/src/main/java/name/mlopatkin/andlogview/utils/MyFutures.java
src/name/mlopatkin/andlogview/ui/device/AdbOpener.java
src/name/mlopatkin/andlogview/ui/device/AdbServicesInitializationPresenter.java
src/name/mlopatkin/andlogview/ui/mainframe/device/AdbInitProgressDialog.java
src/name/mlopatkin/andlogview/ui/mainframe/device/MainFrameAdbInitView.java
test/name/mlopatkin/andlogview/ui/device/AdbServicesInitializationPresenterTest.java

Show adb init progress dialog

---

HISTORY
src/name/mlopatkin/andlogview/liblogcat/file/DumpstateFileDataSource.java
src/name/mlopatkin/andlogview/liblogcat/file/FileDataSourceFactory.java
src/name/mlopatkin/andlogview/liblogcat/file/LogfileDataSource.java
test/name/mlopatkin/andlogview/liblogcat/file/FileDataSourceFactoryTest.java

Properly pass the path to the log/dumpstate file to have valid metadata

---

parsers/src/main/java/name/mlopatkin/andlogview/parsers/logcat/DelegateLong.java
parsers/src/main/java/name/mlopatkin/andlogview/parsers/logcat/RegexLogcatParserDelegate.java
parsers/src/test/java/name/mlopatkin/andlogview/parsers/logcat/DelegateLongTest.java

Fix long parsing with control lines

---

HISTORY
gradle/libs.versions.toml

Start 0.23 release cycle

---

src/name/mlopatkin/andlogview/config/SimpleClient.java
src/name/mlopatkin/andlogview/preferences/AdbConfigurationPref.java

Clean up AdbConfigurationPref

---

base/src/main/java/name/mlopatkin/andlogview/base/collections/MyArrays.java
config/idea/run/Open Dump.run.xml
src/name/mlopatkin/andlogview/AppGlobals.java
src/name/mlopatkin/andlogview/MainFrame.java
src/name/mlopatkin/andlogview/ui/filters/BaseFilterModelAdapter.java
src/name/mlopatkin/andlogview/ui/filters/BaseFilterPresenter.java
src/name/mlopatkin/andlogview/ui/filters/FilterModule.java
src/name/mlopatkin/andlogview/ui/filters/FilterPanelModelAdapter.java
src/name/mlopatkin/andlogview/ui/filters/FilterTreeModelAdapter.java
src/name/mlopatkin/andlogview/ui/filters/PanelFilter.java
src/name/mlopatkin/andlogview/ui/filters/TreeNodeFilter.java
src/name/mlopatkin/andlogview/ui/filtertree/EditAction.java
src/name/mlopatkin/andlogview/ui/filtertree/FilterNodeEditor.java
src/name/mlopatkin/andlogview/ui/filtertree/FilterNodeRenderer.java
src/name/mlopatkin/andlogview/ui/filtertree/FilterNodeViewModel.java
src/name/mlopatkin/andlogview/ui/filtertree/FilterTreeFactory.java
src/name/mlopatkin/andlogview/ui/filtertree/FilterTreeModel.java
src/name/mlopatkin/andlogview/ui/filtertree/TreeModelAdapter.java
src/name/mlopatkin/andlogview/ui/filtertree/package-info.java
test/name/mlopatkin/andlogview/ui/filters/BaseFilterPresenterTest.java

Initial stub at TreeView representation of the log filters

---

src/name/mlopatkin/andlogview/filters/MainFilterController.java
src/name/mlopatkin/andlogview/ui/filters/FilterTreeModelAdapter.java
src/name/mlopatkin/andlogview/ui/filtertree/FilterCreator.java
src/name/mlopatkin/andlogview/ui/filtertree/FilterTreeFactory.java
src/name/mlopatkin/andlogview/ui/filtertree/FilterTreeModel.java
src/name/mlopatkin/andlogview/ui/filtertree/PopupMenu.java
src/name/mlopatkin/andlogview/ui/mainframe/MainFrameModule.java
test/name/mlopatkin/andlogview/ui/filtertree/FakeFilterTreeModel.java
widgets/src/main/java/name/mlopatkin/andlogview/widgets/FixedTreeUi.java
widgets/src/main/java/name/mlopatkin/andlogview/widgets/checktree/CheckFlatTreeUi.java

Popup menu for filter tree

---

build.gradle.kts
config/checkstyle/checkstyle.xml
gradle/libs.versions.toml
src/name/mlopatkin/andlogview/ui/device/SelectDeviceDialogUi.java
src/name/mlopatkin/andlogview/ui/filterdialog/BaseFilterDialogUi.java
src/name/mlopatkin/andlogview/ui/filterdialog/FilteringModesPanel.java
src/name/mlopatkin/andlogview/ui/filterpanel/FilterPanelUi.java
src/name/mlopatkin/andlogview/ui/preferences/ConfigurationDialogUi.java
third-party/libs/notices/com.miglayout.miglayout-core.5.3.NOTICE
third-party/libs/notices/com.miglayout.miglayout-swing.5.3.NOTICE
widgets/build.gradle.kts
widgets/src/main/java/name/mlopatkin/andlogview/widgets/MigConstraints.java

MigLayout is much easier to edit by hand.

Use MigLayout

---

jmh/java/name/mlopatkin/andlogview/ui/filterdialog/FilterFromDialogSingleTagPerfTest.java
src/name/mlopatkin/andlogview/ui/filterdialog/BaseFilterDialogUi.java
src/name/mlopatkin/andlogview/ui/filterdialog/FilterDialog.java
src/name/mlopatkin/andlogview/ui/filterdialog/FilterDialogPresenter.java
src/name/mlopatkin/andlogview/ui/filterdialog/FilterFromDialog.java
src/name/mlopatkin/andlogview/ui/filterdialog/FilterFromDialogData.java
src/name/mlopatkin/andlogview/ui/filterdialog/FilterFromDialogImpl.java
src/name/mlopatkin/andlogview/ui/filterdialog/IndexWindowFilter.java
src/name/mlopatkin/andlogview/ui/filters/FilterDescriptionBuilder.java
src/name/mlopatkin/andlogview/ui/filters/FiltersCodec.java
src/name/mlopatkin/andlogview/ui/filters/PanelFilter.java
src/name/mlopatkin/andlogview/ui/filters/SavedDialogFilterData.java
src/name/mlopatkin/andlogview/ui/filters/SavedFilterData.java
src/name/mlopatkin/andlogview/ui/filters/TreeNodeFilter.java
src/name/mlopatkin/andlogview/ui/filtertree/FilterNodeRenderer.java
src/name/mlopatkin/andlogview/ui/filtertree/FilterNodeTransferHandler.java
src/name/mlopatkin/andlogview/ui/filtertree/FilterNodeViewModel.java
src/name/mlopatkin/andlogview/ui/filtertree/FilterTreeFactory.java
src/name/mlopatkin/andlogview/ui/filtertree/TreeActions.java
src/name/mlopatkin/andlogview/ui/mainframe/popupmenu/TablePopupMenuPresenter.java
test/name/mlopatkin/andlogview/ui/filterdialog/FilterDialogPresenterTest.java
test/name/mlopatkin/andlogview/ui/filterdialog/FilterFromDialogDataTest.java
test/name/mlopatkin/andlogview/ui/filterdialog/FilterMatchers.java
test/name/mlopatkin/andlogview/ui/filterdialog/IndexWindowFilterTest.java
test/name/mlopatkin/andlogview/ui/filters/BaseFilterPresenterTest.java
test/name/mlopatkin/andlogview/ui/filters/IndexWindowFilterDataTest.java
test/name/mlopatkin/andlogview/ui/filters/SavedDialogFilterDataTest.java
test/name/mlopatkin/andlogview/ui/filtertree/FakeFilterTreeModel.java

Introduce named filters

---

src/name/mlopatkin/andlogview/MainFrame.java

Fix potential popup menu leakage

---

HISTORY
src/name/mlopatkin/andlogview/MainFrame.java
src/name/mlopatkin/andlogview/preferences/AdbConfigurationPref.java
src/name/mlopatkin/andlogview/ui/bookmarks/BookmarkController.java
src/name/mlopatkin/andlogview/ui/device/AdbNotAvailableDialog.java
src/name/mlopatkin/andlogview/ui/device/AdbOpener.java
src/name/mlopatkin/andlogview/ui/device/AdbServicesBridge.java
src/name/mlopatkin/andlogview/ui/device/AdbServicesInitializationPresenter.java
src/name/mlopatkin/andlogview/ui/mainframe/ErrorDialogs.java
src/name/mlopatkin/andlogview/ui/mainframe/device/MainFrameAdbInitView.java
test/name/mlopatkin/andlogview/ui/device/AdbServicesBridgeTest.java
test/name/mlopatkin/andlogview/ui/device/AdbServicesInitializationPresenterTest.java
test/name/mlopatkin/andlogview/ui/preferences/ConfigurationDialogPresenterTest.java

Allow suppressing ADB init failure dialog on startup

---

src/name/mlopatkin/andlogview/preferences/AdbConfigurationPref.java
src/name/mlopatkin/andlogview/ui/preferences/ConfigurationDialogPresenter.java
src/name/mlopatkin/andlogview/ui/preferences/ConfigurationDialogView.java
test/name/mlopatkin/andlogview/preferences/AdbConfigurationPrefTest.java
test/name/mlopatkin/andlogview/ui/preferences/ConfigurationDialogPresenterTest.java

Sanitize adb location in the configuration dialog

---

HISTORY
gradle/libs.versions.toml

Start 0.24 release cycle

---

.github/workflows/pull-request-test.yaml
.github/workflows/releasing.yaml
tools/build-environment/Dockerfile

Update JDKs and add jpackage dependency to prepare DEB and RPM packages

---

buildSrc/src/main/kotlin/name/mlopatkin/andlogview/building/installers.gradle.kts

Gradle considered build/distribution an output directory of linuxInstallers even though we were only copying a number of files into it. It overlaps with shadowDistZip's output, and blows up when both installers and bitbucketUpload tasks are present.
An ad-hoc copy implementation that only declares the files as outputs is introduced to fix that.
Issue: #437

Fix overlapping outputs

---

.github/workflows/windows-test.yaml
build.gradle.kts
buildSrc/src/main/kotlin/name/mlopatkin/andlogview/building/BuildEnvironment.kt
buildSrc/src/main/kotlin/name/mlopatkin/andlogview/building/installers.gradle.kts

Support for the Windows installer builds

---

.github/workflows/pull-request-test.yaml
.github/workflows/releasing.yaml
tools/build-environment/Dockerfile

Add GH tool to manage releases

---

.github/workflow-templates/includes/releases.ftlh
.github/workflows/releasing.yaml
docs/releases/release_0.24.md

Wait for mac build to be ready before publishing the nightly release

---

base/build.gradle.kts
buildSrc/src/main/kotlin/name/mlopatkin/andlogview/building/java-conventions.gradle.kts
device/build.gradle.kts
filters/build.gradle.kts
logmodel/build.gradle.kts
parsers/build.gradle.kts
search/build.gradle.kts

Polish java-conventions

---

.github/workflow-templates/includes/releases.ftlh
.github/workflows/releasing.yaml
build.gradle.kts
buildSrc/src/main/kotlin/name/mlopatkin/andlogview/building/BuildEnvironment.kt
buildSrc/src/main/kotlin/name/mlopatkin/andlogview/building/Git.kt
buildSrc/src/main/kotlin/name/mlopatkin/andlogview/building/GitRevCountValueSource.kt
buildSrc/src/main/kotlin/name/mlopatkin/andlogview/building/ProcessUtils.kt
buildSrc/src/main/kotlin/name/mlopatkin/andlogview/building/Version.kt
install/windows/overrides.wxi

Make version number on Windows always increasing, but synthetic

---

gradle/libs.versions.toml
src/name/mlopatkin/andlogview/MainFrame.java
test/name/mlopatkin/andlogview/DataSourceHolderTest.java
test/name/mlopatkin/andlogview/ui/device/AdbServicesBridgeTest.java

Upgrade NullAway to 0.12.9
