mlopatkin/andlogview

.github/workflows/release.yaml
It turns out that you cannot have both tags and tags-ignore. Hope that
ignoring will be enough.
Issue: #175
=> Fix non-snapshot releases

bitbucket-pipelines.yml
We still keep ability to build PRs though to allow contributions there.
Releases are now built on Github, though published to Bitbucket for a
while.
Issue: #175
=> Stop building any releases on Bitbucket Pipelines

buildSrc/src/main/groovy/name/mlopatkin/andlogview/building/BuildEnvironment.groovy, buildSrc/src/main/groovy/name/mlopatkin/andlogview/building/GenerateBuildMetadata.groovy, src/name/mlopatkin/andlogview/Main.java
This isn't a particularly useful thing given the migration to Github
where build numbers started from 1 again.
Issue: #157
=> Remove build number from embedded build info

build.gradle.kts
Without explicit set up the build picks up whatever is set on the files
in the working directory. Turns out it depends on the configuration of
the OS, e.g. on Windows and in the Docker image these are `rw?r-?r-?`
while on my Linux box these are `rw?rw?r-?` (executability depends on
the actual file). This causes hard-to-debug discrepancies so now the
build explicitly discards group-writable attribute.
Fixes #157
=> Use consistent file permissions in archives everywhere

resources/name/mlopatkin/andlogview/logview.properties, src/name/mlopatkin/andlogview/liblogcat/LogRecord.java
The kernel log buffer is still listed as available even in user builds,
but it is always empty there. We have to live with it though.
Issue: #157
=> Support kernel buffer where it is available

src/name/mlopatkin/andlogview/filters/MainFilterController.java, src/name/mlopatkin/andlogview/ui/filterdialog/FilterDialog.java, src/name/mlopatkin/andlogview/ui/filterdialog/FilterDialogFactory.java, src/name/mlopatkin/andlogview/ui/filterdialog/FilterDialogHandle.java, src/name/mlopatkin/andlogview/ui/filterdialog/FilterDialogPresenter.java, test/name/mlopatkin/andlogview/filters/MainFilterControllerTest.java, test/name/mlopatkin/andlogview/ui/filterdialog/FilterDialogPresenterTest.java
While the second editor did nothing, it was still a sub-par UX. New
behavior is much friendlier.
Issue: fixes #155
=> Bring existing filter editor to front when trying to edit it twice

src/name/mlopatkin/andlogview/ui/filterpanel/FilterPanel.java, src/name/mlopatkin/andlogview/ui/filterpanel/FilterPanelUi.java, src/name/mlopatkin/andlogview/ui/themes/BasicWidgetFactory.java, src/name/mlopatkin/andlogview/ui/themes/FlatLafWidgetFactory.java, src/name/mlopatkin/andlogview/ui/themes/ThemedWidgetFactory.java
The JPanel's default FlowLayout adds 5px paddings on top and bottom.
Without any filter buttons it is of no concern as the panel with(out)
buttons has a desired height of 0, so it is stretched out to the size of
the container. When the filter button appears, these paddings are
applied and this caused the FilterPanel to become 10px taller.
The fix is to remove the default paddings from the inner JPanel.
Instead, some paddings were added to the FilterPanel itself to achieve
a more pleasant look.
Additionally, a "revalidate()+repaint()" spell is now used when the
filter is added. Without this, the change in height is not propagated
to the FilterPanel (thought there is no more change in height).
Fixes #218
=> Fix Filter Panel display when going to/from empty panel

.github/workflows/release.yaml
This reverts commit 35dbdb0465e62486b5570435697d64350409e750.
The automated release action is incompatible with RC tags.
=> Revert "Create draft Github release on tag push"

.github/workflows/pull-request-test.yaml, .github/workflows/release-snapshot.yaml, .github/workflows/release.yaml
The OpenJDK images that I was using before are no longer supported. Moreover, the JDK version is also outdated.
Fixes issue #244.
=> Change the build environment on CI to use JDK from Temurin

buildSrc/src/main/kotlin/name/mlopatkin/andlogview/building/GitRevisionValueSource.kt
Fixes cut off title in Main Window.
Signed-off-by: Dzmitry Neviadomski <nevack.d@gmail.com>
=> fix: Remove trailing newline from Git Revision string.

BUILDING.md, build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/name/mlopatkin/andlogview/building/java-conventions.gradle.kts, gradle/libs.versions.toml
Importing into Eclipse doesn't work out-of-the-box and the ROI of fixing it is too small. I hereby proclaim an end of the Eclipse era of the project.
Issue: fixes #285
=> Remove everything related to Eclipse import from build and docs

HISTORY, base/src/jmh/java/name/mlopatkin/andlogview/base/io/LineReaderPerfTest.java, base/src/main/java/name/mlopatkin/andlogview/base/io/LineReader.java, base/src/main/java/name/mlopatkin/andlogview/utils/MyStringUtils.java, base/src/test/java/name/mlopatkin/andlogview/base/io/LineReaderTest.java, base/src/test/java/name/mlopatkin/andlogview/utils/MyStringUtilsLinesTest.java, parsers/src/main/java/name/mlopatkin/andlogview/parsers/dumpstate/BaseDumpstatePushParser.java, parsers/src/main/java/name/mlopatkin/andlogview/parsers/logcat/DelegateLong.java, parsers/src/main/java/name/mlopatkin/andlogview/parsers/logcat/LogcatPushParser.java, parsers/src/main/java/name/mlopatkin/andlogview/parsers/logcat/SingleLineRegexLogcatParserDelegate.java, parsers/src/test/java/name/mlopatkin/andlogview/parsers/logcat/DelegateLongTest.java, parsers/src/test/java/name/mlopatkin/andlogview/parsers/logcat/LogcatParsersTest.java, src/name/mlopatkin/andlogview/liblogcat/file/FileDataSourceFactory.java
I forgot what I had in mind when I was introducing this `\n`-preserving code. It looks like `LONG` logs can be parsed just fine without looking at `\n`.
It might be important when combining multiple entries into one but we don't do that yet. When parsing the last line of the file, it also doesn't matter much.
Issue: #169
=> Don't keep EOLNs when reading logs

settings.gradle.kts
IDEA runner uses PipedInputStream which is not supported with the configuration cache.
Issue: n/a
=> Suppress CC issue when using IDEA to run the app

logmodel/src/main/java/name/mlopatkin/andlogview/logmodel/LogRecord.java, src/name/mlopatkin/andlogview/liblogcat/file/DumpstateFileDataSource.java, test/name/mlopatkin/andlogview/liblogcat/file/FileDataSourceFactoryTest.java, test_resources/name/mlopatkin/andlogview/liblogcat/file/emulator_api34.minimized.dump
Some dumpstates have process information after the logcat sections, so additional pass is needed to make sure LogRecords are properly configured.
Fixes #279
=> Post-process log records of dumpstate to assign process names

parsers/src/main/java/name/mlopatkin/andlogview/parsers/dumpstate/DumpstateElements.java, parsers/src/test/java/name/mlopatkin/andlogview/parsers/dumpstate/DumpstateElementsTest.java, src/name/mlopatkin/andlogview/liblogcat/file/DumpstateFileDataSource.java
* EVENT LOG TAGS section of ancient android versions was tripping over the parser, which attempted to read it as an event log
* PROCESSES section is reported to be very variable in the wild, though I don't have hands-on dumpstates with such logs.
Fixes #119
=> Fix parsing of some tricky process and logcat sections

settings.gradle.kts
Gradle 8.7 now supports System.in natively and the workaround is no longer needed.
=> Remove unneeded CC workaround for main() task

logmodel/src/main/java/name/mlopatkin/andlogview/logmodel/DataSource.java, logmodel/src/main/java/name/mlopatkin/andlogview/logmodel/Field.java, logmodel/src/testFixtures/java/name/mlopatkin/andlogview/logmodel/AssertLogRecord.java, parsers/src/main/java/name/mlopatkin/andlogview/parsers/logcat/Format.java, parsers/src/main/java/name/mlopatkin/andlogview/parsers/logcat/LogcatPushParser.java, parsers/src/testFixtures/java/name/mlopatkin/andlogview/parsers/logcat/LogcatEntryJsonModel.java, search/logrecord/src/main/java/name/mlopatkin/andlogview/search/logrecord/OrSearcher.java, search/logrecord/src/main/java/name/mlopatkin/andlogview/search/logrecord/RowSearchStrategy.java, search/logrecord/src/main/java/name/mlopatkin/andlogview/search/logrecord/RowSearchStrategyFactory.java, search/logrecord/src/main/java/name/mlopatkin/andlogview/search/logrecord/ValueSearcher.java, src/name/mlopatkin/andlogview/liblogcat/ddmlib/AdbDataSource.java, src/name/mlopatkin/andlogview/liblogcat/file/DumpstateFileDataSource.java, src/name/mlopatkin/andlogview/liblogcat/file/LogfileDataSource.java, src/name/mlopatkin/andlogview/ui/logtable/Column.java
Java enum cannot have subtypes as its constants or be a generic, but this is somewhat desirable for the Field constants. This commit rewrites the enum into a pre-Java-5 style class-with-constants implementation to achieve the necessary type safety. Not that it is strictly necessary...
Issue: n/a
=> Increase type safety of Field class

base/src/main/java/name/mlopatkin/andlogview/utils/SystemPathResolver.java, base/src/main/java/name/mlopatkin/andlogview/utils/properties/ListPropertyBuilder.java, base/src/test/java/name/mlopatkin/andlogview/utils/ListTestUtils.java, buildSrc/src/main/kotlin/name/mlopatkin/andlogview/building/BuildEnvironment.kt, buildSrc/src/main/kotlin/name/mlopatkin/andlogview/building/java-conventions.gradle.kts, device/src/main/java/name/mlopatkin/andlogview/device/DeviceTempFile.java, device/src/main/java/name/mlopatkin/andlogview/device/OutputTarget.java, device/src/test/java/name/mlopatkin/andlogview/device/DispatchingDeviceListTest.java, parsers/src/main/java/name/mlopatkin/andlogview/parsers/MultiplexParser.java, search/src/testFixtures/java/name/mlopatkin/andlogview/search/ListSearchModel.java
=> Enable extra javac warnings

base/src/main/java/name/mlopatkin/andlogview/base/collections/MyIterables.java, base/src/main/java/name/mlopatkin/andlogview/utils/events/LazySubject.java, filters/src/main/java/name/mlopatkin/andlogview/filters/ChildModelFilter.java, filters/src/main/java/name/mlopatkin/andlogview/filters/CompoundFilterModel.java, filters/src/main/java/name/mlopatkin/andlogview/filters/FilterChain.java, filters/src/main/java/name/mlopatkin/andlogview/filters/FilterModel.java, filters/src/main/java/name/mlopatkin/andlogview/filters/FilterModelImpl.java, filters/src/main/java/name/mlopatkin/andlogview/filters/MutableFilterModel.java, filters/src/test/java/name/mlopatkin/andlogview/filters/CompoundFilterModelTest.java, filters/src/test/java/name/mlopatkin/andlogview/filters/MutableFilterModelTest.java, filters/src/testFixtures/java/name/mlopatkin/andlogview/filters/Filters.java, filters/src/testFixtures/java/name/mlopatkin/andlogview/filters/TestChildModelFilter.java, src/name/mlopatkin/andlogview/ui/filterdialog/IndexWindowFilter.java, src/name/mlopatkin/andlogview/ui/filters/IndexWindowFilterData.java, src/name/mlopatkin/andlogview/ui/indexfilter/IndexFilterController.java, test/name/mlopatkin/andlogview/ui/filterdialog/IndexWindowFilterTest.java, test/name/mlopatkin/andlogview/ui/filters/IndexWindowFilterDataTest.java
The index filter window is now affected only by the filters that were added before it. Combined with filter reordering, this may improve the usability.
You need to enable new UI (with a listview) for this feature to work.
Fixes #164.
=> Make Index Filter order sensitive

filters/build.gradle.kts, filters/src/main/java/name/mlopatkin/andlogview/filters/BufferFilter.java, filters/src/test/java/name/mlopatkin/andlogview/filters/BufferFilterTest.java, filters/src/testFixtures/java/name/mlopatkin/andlogview/filters/AbstractToggleFilter.java, filters/src/testFixtures/java/name/mlopatkin/andlogview/filters/ColoringToggleFilter.java, filters/src/testFixtures/java/name/mlopatkin/andlogview/filters/Filters.java, filters/src/testFixtures/java/name/mlopatkin/andlogview/filters/ToggleFilter.java, src/name/mlopatkin/andlogview/ui/filterdialog/FilterFromDialogImpl.java, src/name/mlopatkin/andlogview/ui/filterdialog/IndexWindowFilter.java, test/name/mlopatkin/andlogview/filters/FilterChainTest.java, test/name/mlopatkin/andlogview/filters/LogRecordHighlighterTest.java, test/name/mlopatkin/andlogview/ui/filters/IndexWindowFilterDataTest.java, test/name/mlopatkin/andlogview/ui/filters/SavedDialogFilterDataTest.java
This allows to have duplicate filters in model and avoids some nasty situations when none-identical filters become identical after editing or toggling.
Thinking more about it, it makes sense to have two index filters with the same filters, but different positions, because they are position-sensitive now.
Issue: fixes #372, fixes #389
=> Use identity for filter comparisons

device/src/main/java/name/mlopatkin/andlogview/device/AdbServerImpl.java, device/src/main/java/name/mlopatkin/andlogview/device/DeviceProvisioner.java, device/src/main/java/name/mlopatkin/andlogview/device/DeviceProvisionerImpl.java, device/src/test/java/name/mlopatkin/andlogview/device/DeviceProvisionerImplTest.java, device/src/test/java/name/mlopatkin/andlogview/device/DispatchingDeviceListTest.java, device/src/test/java/name/mlopatkin/andlogview/device/FakeDeviceProvisioner.java
=> Do not leak provisional device observer when changing ADB servers
